name       : kdenetwork-filesharing
version    : 20.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kdenetwork-filesharing-20.12.2.tar.xz : 3ffe68bb7888c6302adae8b8849a7515b0460662071ec5370c0d4e98c057c078
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
