name       : kdenetwork-filesharing
version    : 21.08.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kdenetwork-filesharing-21.08.2.tar.xz : 8cdb0585a44c83c62f3f102530548162ab334fda40b7966e9640adc34381d777
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
