name       : kdenetwork-filesharing
version    : 21.12.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kdenetwork-filesharing-21.12.1.tar.xz : 9e8dc8f6680d6477819df06d1cbbeac7313a15d308879e05ccd4578b3010e713
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
