name       : kdenetwork-filesharing
version    : 18.12.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kdenetwork-filesharing-18.12.3.tar.xz : 296c71526de0e51b4385962c76c2870cfe344b9dafdd2f5f2fba81801350d503
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
