name       : kdenetwork-filesharing
version    : 19.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/kdenetwork-filesharing-19.04.2.tar.xz : e612e3e1cd85f80e73dbce0fd749506424418d308b0bb3e4aca43aa4436224a3
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
