name       : kdenetwork-filesharing
version    : 22.12.1
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kdenetwork-filesharing-22.12.1.tar.xz : 33324b2e09ecc163d5eb284e3f1ec2ee15fdb53362035fa6a656db21adfc8c57
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
