name       : kdenetwork-filesharing
version    : 20.12.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kdenetwork-filesharing-20.12.0.tar.xz : cc0f8554e3b0ed2654d7bcfddad1fd8b5714b1852458b66775b7bcf7e9df565d
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
