name       : kdenetwork-filesharing
version    : 21.04.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kdenetwork-filesharing-21.04.1.tar.xz : 894828a5fa14d05d6ea8f9d59954fb5e71b1412074305dfbb9d7477550c2c5ff
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
