name       : kdenetwork-filesharing
version    : 18.08.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kdenetwork-filesharing-18.08.2.tar.xz : fc1b6b6032cbb7082d9e6db70cccf6c62e5e6f296f2c46a5ab8760a2fd734fd9
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
