name       : kdenetwork-filesharing
version    : 18.08.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kdenetwork-filesharing-18.08.0.tar.xz : c75c34459a42bc2b16265cd8f51ba3640b795498a9c579504e1a4ccd9d4bae50
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
