name       : kdenetwork-filesharing
version    : 20.08.2
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kdenetwork-filesharing-20.08.2.tar.xz : f909ee8433baf906b6c23af4747d83ae3e151e213585abe01282213012228b3a
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
optimize   : lto
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
