name       : kdenetwork-filesharing
version    : 21.08.3
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kdenetwork-filesharing-21.08.3.tar.xz : a959d611e5538b63f867d9b781e6e4279d0d2d3868eae3a8d263f51481af83a5
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
