name       : kdenetwork-filesharing
version    : 22.08.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kdenetwork-filesharing-22.08.3.tar.xz : 410921ed792f9c4f46ea687485342efc7cb1debd72617674901b46a7dbc4a80d
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
