name       : kdenetwork-filesharing
version    : 23.04.1
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kdenetwork-filesharing-23.04.1.tar.xz : 91db205a7dd60840678b571bfcb4a30daa78602ba0eb418fd3ae8699ceacefc1
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
    - qcoro-qt5-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
