name       : kdenetwork-filesharing
version    : 21.04.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kdenetwork-filesharing-21.04.0.tar.xz : 4df5d8d8e1dd9981936221dff145fa874ecf077183742c5374ee38b9a9bb491d
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.clients
summary    : Network file sharing integration for dolphin
description: |
    Network file sharing integration for dolphin.
optimize   : lto
builddeps  :
    - kdeclarative-devel
    - kio-devel
setup      : |
    %cmake_ninja -DSAMBA_INSTALL=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
